apiVersion: v1
kind: Service
metadata:
  labels: 
    app: jenkins
  name: jenkins
  namespace: vote
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 81
    nodePort: 31003
  selector:
    app: jenkins
